{ pkgs, ... }:
{
  # fix edid for Legion 5 Pro AMDGPU
  # extract from nvidia passthrogh
  hardware.display.edid = {
    enable = true;
    packages = [
      (pkgs.runCommand "edid-custom" { } ''
            mkdir -p "$out/lib/firmware/edid"
            base64 -d > "$out/lib/firmware/edid/edid_2560x1600.bin" <<'EOF'
            AP///////wAObwAWAAAAAAAeAQS1IhZ4A+6Vo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEBbm4AoKBAhGAwIDYAWdcQAAAYAAAA/Qw8pR8fTgEKICAgICAgAAAA/gBDU09UIFQzCiAgICAgAAAA/gBNTkcwMDdEQTEtMQogAgICAx0A4wWAAOYGBQFqaiRtGgAAAgM8pQAEaiRqJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/3ATeQAAAwEUrC8Bhf8JnwAvAB8APwaDAAIABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeQ
            EOF
      '')
    ];
  };
}

